### ISSUE TITLE
Ability to provide an ContextMenu handler to the MenuWindow's child

### ISSUE THREAD

**Issue by akhilpanchal** [erictooth/react-menu-window#1]
**Use case:**
On context clicking the MenuWindow's child, want to be able perform an action.
Ex: A Context Click on a Table Row should also "select" the row apart from displaying the context menu. 

**Approach:**
I am providing a `onContextMenu` prop to the MenuWindow's child that performs some action.

**Current Behavior:**
MenuWindow clones the child and provides a [onContextMenu handler](https://github.com/erictooth/react-menu-window/blob/78b8fb60e27fc874175e5e059d9c5ed87d80eacc/src/index.tsx#L36
) that overrides the exiting onContextMenu handler 

We could probably call the consumer provided handler inside handleContextMenu

Any thoughts or suggestions?

**Comment by erictooth** [comment]
Merged -- thanks!
