### ISSUE TITLE
Pass `event` object to the `shouldOpen` prop 

### ISSUE THREAD

**Issue by akhilpanchal** [erictooth/react-menu-window#3]
Hello:

We have a use-case where we want to programmatically control when the context menu opens based on the `event.target`.
The only way to do that would be to write the logic inside the `shouldOpen` callback prop. Currently, [we do not pass any arguments while calling the `shouldOpen` function.](
https://github.com/erictooth/react-menu-window/blob/b32b660dfcf3b3c4f2c17146bdc50bbc4d25e68a/src/index.tsx#L62)

Does this seem like a reasonable requirement?
I can contribute a fix for this.

**Comment by erictooth** [comment]
Closed by #4
